#!/bin/bash

# Diagnostic: Why IP is still 127.0.0.1?
# This script helps diagnose IP detection issues

echo "================================================"
echo "IP Address Detection Diagnostic"
echo "================================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${YELLOW}Question 1: Where are you testing?${NC}"
echo ""
echo "A) On my LOCAL machine (Mac/Windows) - http://localhost:3001"
echo "B) On EC2 server via public IP - http://your-ec2-ip:3001"
echo "C) On EC2 server via domain - http://yourdomain.com"
echo ""
echo -e "${RED}⚠️  IMPORTANT:${NC}"
echo "If you answered A (localhost), seeing 127.0.0.1 is CORRECT!"
echo "You need to test via EC2 public IP or domain to see real IPs."
echo ""
echo "================================================"
echo ""

echo -e "${YELLOW}Question 2: Have you deployed to EC2?${NC}"
echo ""
echo "The fix is in your code, but you need to deploy it:"
echo ""
echo -e "${BLUE}Run on EC2:${NC}"
echo "cd ~/fyp_system && git pull origin main"
echo "cd backend && npm run build"
echo "pm2 restart backend"
echo ""
echo "================================================"
echo ""

echo -e "${YELLOW}Question 3: Is your architecture using Nginx?${NC}"
echo ""
echo "Check if requests go through Nginx proxy:"
echo ""
echo -e "${BLUE}On EC2, check Nginx status:${NC}"
echo "sudo systemctl status nginx"
echo "sudo nginx -t"
echo ""
echo "If Nginx is NOT running, you'll see 127.0.0.1"
echo ""
echo "================================================"
echo ""

echo -e "${YELLOW}Quick Tests:${NC}"
echo ""
echo "1. Test LOCAL (will show 127.0.0.1 or ::1):"
echo -e "   ${BLUE}http://localhost:3001${NC}"
echo "   Expected IP: 127.0.0.1 ✅ (this is normal)"
echo ""
echo "2. Test EC2 via public IP (will show real IP):"
echo -e "   ${BLUE}http://your-ec2-public-ip:3001${NC}"
echo "   Expected IP: Your ISP's public IP ✅"
echo ""
echo "3. Test from mobile/different network:"
echo "   Open browser on phone → EC2 IP"
echo "   Expected IP: Mobile network IP ✅"
echo ""
echo "================================================"
echo ""

echo -e "${GREEN}Most Common Issues:${NC}"
echo ""
echo "❌ Issue: Testing on localhost"
echo "   ✅ Solution: Test via EC2 public IP"
echo ""
echo "❌ Issue: Haven't deployed to EC2"
echo "   ✅ Solution: Run deployment commands"
echo ""
echo "❌ Issue: Nginx not running"
echo "   ✅ Solution: sudo systemctl start nginx"
echo ""
echo "❌ Issue: Frontend calling backend directly (not via proxy)"
echo "   ✅ Solution: Check frontend API calls use relative paths"
echo ""
echo "================================================"
echo ""

echo -e "${YELLOW}Debugging Commands for EC2:${NC}"
echo ""
echo "# Check if trust proxy is enabled (look for the line)"
echo -e "${BLUE}pm2 logs backend | grep 'trust proxy'${NC}"
echo ""
echo "# Check backend is receiving correct headers"
echo -e "${BLUE}pm2 logs backend --lines 50${NC}"
echo ""
echo "# Check Nginx is forwarding headers"
echo -e "${BLUE}sudo tail -f /var/log/nginx/access.log${NC}"
echo ""
echo "# Test with curl (should show your IP)"
echo -e "${BLUE}curl -H 'X-Real-IP: 1.2.3.4' http://localhost:3000/revenue${NC}"
echo ""
echo "================================================"
echo ""

echo -e "${RED}KEY INSIGHT:${NC}"
echo ""
echo "If you're seeing 127.0.0.1, it's likely because:"
echo ""
echo "1. You're testing on LOCAL machine (localhost)"
echo "   → This is EXPECTED behavior"
echo "   → Test via EC2 public IP instead"
echo ""
echo "2. You haven't deployed the fix to EC2 yet"
echo "   → Pull latest code and rebuild"
echo ""
echo "3. Your frontend is calling backend directly"
echo "   → Should use Next.js proxy (/api/*)"
echo ""
echo "================================================"
echo ""

echo -e "${GREEN}Next Steps:${NC}"
echo ""
echo "1. Deploy to EC2 if you haven't:"
echo "   cd ~/fyp_system && git pull && cd backend && npm run build && pm2 restart backend"
echo ""
echo "2. Test via EC2 public IP (not localhost):"
echo "   http://your-ec2-ip:3001"
echo ""
echo "3. Check audit logs after testing from EC2"
echo ""
