#!/bin/bash
# FINAL DEPLOYMENT - Complete Audit System
# All fixes included: Silent parameter + Real IP + Clean IPv4 + Delete feature

echo "================================================"
echo "🚀 FINAL DEPLOYMENT - Complete Audit System"
echo "================================================"
echo ""
echo "This deployment includes ALL fixes:"
echo "✅ Silent parameter (no VIEW_REVENUE noise)"
echo "✅ Real IP detection (no 127.0.0.1)"
echo "✅ Clean IPv4 format (no ::ffff:)"
echo "✅ Delete individual logs"
echo "✅ Clear all logs (with OTP)"
echo ""
echo "================================================"
echo ""

read -p "Press Enter to start deployment on EC2..."

echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1️⃣  SSH to EC2:"
echo "    ssh -i your-key.pem ubuntu@your-ec2-ip"
echo ""
echo "2️⃣  Pull latest code:"
echo "    cd ~/fyp_system && git pull origin main"
echo ""
echo "3️⃣  Rebuild backend:"
echo "    cd backend && npm run build"
echo ""
echo "4️⃣  Rebuild frontend:"
echo "    cd ../frontend && npm run build"
echo ""
echo "5️⃣  Restart services:"
echo "    pm2 restart all"
echo ""
echo "6️⃣  Verify:"
echo "    pm2 status && pm2 logs backend --lines 20"
echo ""
echo "================================================"
echo ""

echo "🎯 QUICK ONE-LINER (copy-paste this):"
echo ""
echo "cd ~/fyp_system && git pull origin main && cd backend && npm run build && cd ../frontend && npm run build && pm2 restart all && pm2 status"
echo ""
echo "================================================"
echo ""

echo "✅ TESTING CHECKLIST:"
echo ""
echo "Test 1: IP Format"
echo "  • Perform any action"
echo "  • Check IP in audit log"
echo "  • Expected: 113.211.126.75 (clean format)"
echo "  • NOT: 127.0.0.1 or ::ffff:113.211.126.75"
echo ""
echo "Test 2: Silent Parameter"
echo "  • Create/update/delete revenue"
echo "  • Check audit log"
echo "  • Expected: Only CRUD action, no extra VIEW_REVENUE"
echo ""
echo "Test 3: Delete Individual"
echo "  • Click Delete on any log"
echo "  • Click Confirm"
echo "  • Expected: Log deleted, DELETE_AUDIT_LOG recorded"
echo ""
echo "Test 4: Clear All"
echo "  • Click 'Clear All Logs' button"
echo "  • Enter password"
echo "  • Enter OTP from email"
echo "  • Expected: All logs cleared, CLEAR_ALL_AUDIT_LOGS recorded"
echo ""
echo "================================================"
echo ""

echo "📚 DOCUMENTATION:"
echo ""
echo "Read these files for complete information:"
echo "  • COMPLETE_AUDIT_SYSTEM_SUMMARY.md"
echo "  • AUDIT_LOG_SILENT_PARAMETER.md"
echo "  • REAL_IP_DETECTION_FIX.md"
echo "  • NEXTJS_PROXY_IP_FORWARDING_FIX.md"
echo "  • FIX_IPV4_MAPPED_FORMAT.md"
echo "  • AUDIT_LOG_DELETE_FEATURE.md"
echo ""
echo "================================================"
echo ""

echo "🎉 DEPLOYMENT READY!"
echo "All code is committed and pushed to GitHub."
echo "Follow the steps above to deploy to EC2."
echo ""
