#!/bin/bash
# Quick commands to run on EC2 server

echo "🚀 COPY AND PASTE THESE COMMANDS ON YOUR EC2 SERVER:"
echo "=================================================="
echo ""
echo "cd ~/fyp_system"
echo "git stash push -m 'EC2 local changes before fix'"
echo "git pull origin main"
echo "ls -lh frontend/app/purchase-requests/page.tsx"
echo "cd frontend"
echo "npm install"
echo "rm -rf .next node_modules/.cache"
echo "npm run build | grep purchase-requests"
echo "pm2 restart frontend"
echo "pm2 logs frontend --lines 30 --nostream"
echo "curl -I http://localhost:3001/purchase-requests"
echo ""
echo "=================================================="
echo "✅ If you see HTTP/1.1 200 OK, the fix is deployed!"
