#!/bin/bash

# Test Script for Claim Upload Security Features
# Tests the three main security features:
# 1. Upload button disabled after claim submission
# 2. Duplicate file prevention across requests
# 3. ClamAV malware scanning

echo "=============================================="
echo "Claim Upload Security Feature Tests"
echo "=============================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Prerequisites:${NC}"
echo "1. Backend running on http://localhost:3000"
echo "2. Frontend running on http://localhost:3001"
echo "3. Database accessible and migrated"
echo "4. ClamAV daemon running (clamd)"
echo "5. Valid user credentials for testing"
echo ""

read -p "Press Enter to continue with manual testing instructions..."
echo ""

echo "=============================================="
echo -e "${BLUE}TEST 1: Upload Button Disabled After Submission${NC}"
echo "=============================================="
echo ""
echo "Steps:"
echo "1. Login as sales_department user"
echo "2. Create a new purchase request"
echo "3. Login as accountant and approve the request with an approved amount"
echo "4. Login back as sales_department user"
echo "5. Navigate to Purchase Requests page"
echo "6. Find the approved request - should see 'Upload Claim' button"
echo "7. Click 'Upload Claim' button"
echo "8. Fill in all fields and upload a receipt file (PDF/JPG/PNG)"
echo "9. You should see: '🔍 Scanning file for malware and validating... Please wait.'"
echo "10. Enter password to get OTP"
echo "11. Enter OTP and submit"
echo "12. Button should show: '🔍 Scanning & Uploading...'"
echo ""
echo -e "${GREEN}Expected Result:${NC}"
echo "- Upload succeeds"
echo "- Modal closes"
echo "- 'Upload Claim' button disappears"
echo "- '✓ Claim Submitted' badge appears"
echo "- Refresh page - button should still be hidden"
echo ""
read -p "Press Enter to continue to next test..."
echo ""

echo "=============================================="
echo -e "${BLUE}TEST 2: Duplicate File Prevention${NC}"
echo "=============================================="
echo ""
echo "Steps:"
echo "1. Create Request A and get it approved"
echo "2. Upload a receipt (e.g., receipt1.pdf) to Request A"
echo "3. Create Request B and get it approved"
echo "4. Try to upload the SAME receipt (receipt1.pdf) to Request B"
echo ""
echo -e "${GREEN}Expected Result:${NC}"
echo "- Should see error message:"
echo "  'This receipt file has already been uploaded for claim ID: XXX"
echo "   (Purchase Request: [Request A Title]). Duplicate receipts are not allowed.'"
echo ""
echo "5. Try uploading a DIFFERENT receipt (receipt2.pdf) to Request B"
echo ""
echo -e "${GREEN}Expected Result:${NC}"
echo "- Should succeed with no errors"
echo ""
read -p "Press Enter to continue to next test..."
echo ""

echo "=============================================="
echo -e "${BLUE}TEST 3: ClamAV Malware Scanning${NC}"
echo "=============================================="
echo ""
echo "Steps:"
echo "1. Check if ClamAV daemon is running:"
echo "   On macOS: brew services list | grep clamav"
echo "   On Linux: systemctl status clamav-daemon"
echo ""

# Check ClamAV status
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Checking ClamAV status on macOS..."
    brew services list 2>/dev/null | grep clamav || echo -e "${RED}ClamAV not found. Install with: brew install clamav${NC}"
else
    echo "Checking ClamAV status on Linux..."
    systemctl status clamav-daemon 2>/dev/null || echo -e "${RED}ClamAV not running${NC}"
fi
echo ""

echo "2. Create a test file to scan:"
echo "   - Clean file: Any regular PDF or image"
echo "   - Test malware: EICAR test file (safe test virus)"
echo "     Visit: https://www.eicar.org/download-anti-malware-testfile/"
echo ""
echo "3. Upload clean file to a purchase request"
echo ""
echo -e "${GREEN}Expected Result:${NC}"
echo "- Should see scanning feedback: '🔍 Scanning file for malware and validating...'"
echo "- Upload should succeed"
echo ""
echo "4. Try uploading EICAR test file (if ClamAV is running)"
echo ""
echo -e "${GREEN}Expected Result:${NC}"
echo "- Should see error: 'File failed security scan. The uploaded file may contain malware or viruses.'"
echo "- File should NOT be saved to disk"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "=============================================="
echo -e "${BLUE}TEST 4: One Claim Per Request${NC}"
echo "=============================================="
echo ""
echo "Steps:"
echo "1. Upload a claim to Request A"
echo "2. Try to upload ANOTHER claim to the same Request A"
echo ""
echo -e "${GREEN}Expected Result:${NC}"
echo "- Should see error: 'A claim has already been submitted for this purchase request. Only one claim per purchase request is allowed.'"
echo "- Upload button should be hidden anyway, but if you try via API, should be blocked"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "=============================================="
echo -e "${BLUE}TEST 5: User Experience Features${NC}"
echo "=============================================="
echo ""
echo "Verify the following UI elements:"
echo ""
echo "1. Security Notice (in upload modal):"
echo "   - Should see blue box with:"
echo "     '🔒 Security: All files are scanned for malware and checked for duplicates."
echo "      Each receipt can only be used once across all requests.'"
echo ""
echo "2. Scanning Feedback:"
echo "   - During upload, error box should be blue (not red)"
echo "   - Should show: '🔍 Scanning file for malware and validating... Please wait.'"
echo ""
echo "3. Submit Button:"
echo "   - While uploading: '🔍 Scanning & Uploading...'"
echo "   - Normal state: 'Submit Claim'"
echo ""
echo "4. Error Messages:"
echo "   - Duplicate file: Clear error with claim ID and request name"
echo "   - Malware: 'File failed security scan...'"
echo "   - Already claimed: 'A claim has already been submitted...'"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "=============================================="
echo -e "${BLUE}API TESTING (Optional - for developers)${NC}"
echo "=============================================="
echo ""
echo "You can also test the API directly using curl or the test.http file"
echo ""
echo "Example: Testing duplicate file upload"
echo ""
echo "# Step 1: Upload file to Request A"
echo 'curl -X POST http://localhost:3000/purchase-requests/claims/upload \'
echo '  -H "Authorization: Bearer YOUR_JWT_TOKEN" \'
echo '  -F "receipt=@/path/to/receipt.pdf" \'
echo '  -F "purchase_request_id=REQUEST_A_ID" \'
echo '  -F "vendor_name=Test Vendor" \'
echo '  -F "amount_claimed=100" \'
echo '  -F "purchase_date=2025-12-26" \'
echo '  -F "claim_description=Test claim" \'
echo '  -F "otp=123456"'
echo ""
echo "# Step 2: Try to upload same file to Request B"
echo "# Should return 400 error with duplicate message"
echo ""
read -p "Press Enter to finish..."
echo ""

echo "=============================================="
echo -e "${GREEN}Testing Complete!${NC}"
echo "=============================================="
echo ""
echo "Summary of Security Features:"
echo "✅ Upload button disabled after claim submission"
echo "✅ Duplicate file prevention (SHA-256 hash check)"
echo "✅ ClamAV malware scanning"
echo "✅ One claim per purchase request"
echo "✅ User feedback during scanning"
echo "✅ Clear error messages"
echo ""
echo "All features should be working as expected!"
echo ""
echo "For deployment to EC2:"
echo "1. Ensure all builds are complete (frontend & backend)"
echo "2. Push changes to git"
echo "3. SSH to EC2 and pull latest changes"
echo "4. Restart PM2: pm2 restart ecosystem.config.js --update-env"
echo "5. Verify ClamAV is running on EC2"
echo ""
echo "Done! 🚀"
