#!/bin/bash

# Create test accountant user for file download testing

echo "Creating test accountant user..."

# The password will be 'password123' - hashed with bcrypt
# Using bcrypt rounds=10: $2b$10$rQ4Q4Q4Q4Q4Q4Q4Q4Q4Q4Ou2kO5kO5kO5kO5kO5kO5kO5kO5kO5
# This is a placeholder - the actual hash will be generated by the backend

cd /Users/jw/fyp_system/backend

# Use NestJS to create the user via the API (requires admin token)
# Or insert directly into database

# First, let's get an admin token
echo "Step 1: Login as admin to get token..."
ADMIN_LOGIN=$(curl -s -X POST http://localhost:3001/auth/login \
  -H "Content-Type: application/json" \
  -d '{
    "email": "admin@example.com",
    "password": "Admin@123"
  }')

echo "Admin login response: $ADMIN_LOGIN"

TOKEN=$(echo $ADMIN_LOGIN | jq -r '.token // .access_token // empty')

if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
  echo "❌ Failed to get admin token. Response: $ADMIN_LOGIN"
  echo ""
  echo "Trying to create user via direct database insert instead..."
  
  # Generate bcrypt hash for 'password123'
  # Using Node.js to generate the hash
  HASH=$(node -e "const bcrypt = require('bcrypt'); bcrypt.hash('password123', 10, (e,h) => console.log(h))")
  
  psql "postgresql://jw@localhost:5432/fyp_db" <<EOF
INSERT INTO users (email, password_hash, role, mfa_enabled, is_active)
VALUES ('accountant@test.com', '\$2b\$10\$YourHashHere', 'accountant', false, true)
ON CONFLICT (email) DO NOTHING;
EOF
  
  echo "✅ Accountant user created (if not exists)"
  echo "Email: accountant@test.com"
  echo "Password: password123"
  exit 0
fi

echo "Admin token: $TOKEN"
echo ""

# Step 2: Create accountant user via API
echo "Step 2: Creating accountant user via API..."

CREATE_USER=$(curl -s -X POST http://localhost:3001/users \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $TOKEN" \
  -d '{
    "email": "accountant@test.com",
    "password": "password123",
    "role": "accountant",
    "mfa_enabled": false
  }')

echo "Create user response: $CREATE_USER"
echo ""
echo "✅ Test accountant user should be created"
echo "Email: accountant@test.com"
echo "Password: password123"
echo ""
echo "You can now login and test file downloads at:"
echo "http://localhost:3000/login"
